#!/bin/bash

type=$1
front=jacqueline-chen

dir=${front}-${type}
if [ ! -d $dir ]; then
    mkdir $dir
fi

filefront=${front}-${type}
texfile=${filefront}.tex
dvifile=${filefront}.dvi
pdffile=${filefront}.pdf

./jackieletter.py $type > ${dir}/${texfile}
cd $dir
latex $texfile
dvipdfm -o $pdffile $dvifile
open $pdffile
