
texfile := 2015-12-15-group-meeting

default: pdf


pdf:
	pdflatex ${texfile}

clean:
	rm -f \
	${texfile}.dvi \
	${texfile}.ps \
	${texfile}.nav \
	${texfile}.out \
	${texfile}.snm \
	${texfile}.pdf \
	${texfile}.aux \
	${texfile}.bbl \
	${texfile}.blg \
	${texfile}.toc \
	${texfile}.log
