
texfile := 2014-04-fnal
default: pdf

pdf:
	pdflatex ${texfile}

clean:
	rm -f \
	${texfile}.pdf \
	${texfile}.aux \
	${texfile}.toc \
	${texfile}.nav \
	${texfile}.out \
	${texfile}.snm \
	${texfile}.log
